version: "3.7"
services:
  server:
    container_name: ts-express
    ports:
      - "5000:5000"
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
